services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres-db_demo
    environment:
      - POSTGRES_USER=emd_user
      - POSTGRES_PASSWORD=emd_password
      - POSTGRES_DB=emd_demo
    ports:
      - "5435:5432"
    volumes:
      - postgres-data_emd:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: emd_node-backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=emd_user
      - DB_PASSWORD=emd_password
      - DB_NAME=emd_demo
    depends_on:
      - postgres
    networks:
      - app-network
    restart: unless-stopped

volumes:
  postgres-data_emd:

networks:
  app-network:
    driver: bridge
